export const SIGNUP_USER = 'SIGNUP_USER';
export const AUTH_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const NO_INTERNET = 'NO_INTERNET';
export const SERVER_ERROR = 'SERVER_ERROR';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const GENERAL_ERROR = 'GENERAL_ERROR';
